apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: cron-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: cron-event-source
      eventName: daily-schedule-source
  triggers:
    - template:
        name: workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: whalesay-workflow-
              spec:
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      image: docker/whalesay
                      command: [cowsay]
                      args: ["Hello from Argo Events!"]



                      