apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: cron-event-source
  namespace: argo-events
spec:
  calendar:
    daily-schedule-source:
      schedule: "* * * * *"
      payload: '{"message": "Hello, Argo!"}'